### ISSUE TITLE
Failed to load dynamic library 'libtdjson.so': dlopen failed: library "libtdjson.so" not found

### ISSUE THREAD

**Issue by fasteris** [azkadev/azkagram#1]
Hi! I'm currently learning how to use tdlib and your package too.
I was trying to launch azkagram on windows with android emulator but was getting an error:
`Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libtdjson.so': dlopen failed: library "libtdjson.so" not found`

Can you please describe how to use or import libtdjson file, where to store it etc.. Or add small guide on your wiki page

Thank you, good work on azkagram!

**Comment by azkadev** [comment]
Add this in azkagram/android/app/build.gradle

```
main {
    jniLibs.srcDirs = ['src/tdlib']
}
```

and add tdlib file to 
azkagram/android/src/tdlib/

https://github.com/azkadev/telegram_client/releases/tag/v2021.12.22.11.58.01


Sorry my English and communication skills are bad
